package calculator.GUI;

import java.util.ArrayList;

import javax.swing.JPanel;

import logic.Calculator.Polynomial;
import logic.Parser.Tokenizer;

import facade.Facade;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author cristianlinux
 */
public class CaculatorInterface extends javax.swing.JFrame {

	private Facade facade;
	private ArrayList<String> _operator;
	private ArrayList<Polynomial> _polynomialList;
	private ArrayList<Polynomial> _tmpPolynomials;
	private Tokenizer myTokenizer;
    /**
     * Creates new form CaculatorInterface
     */
    public CaculatorInterface() {
    	facade = new Facade();
        _operator = new ArrayList<>();
        _polynomialList = new ArrayList<>();
        _tmpPolynomials = new ArrayList<>();
        myTokenizer = new Tokenizer();
        initComponents();        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Button_7 = new javax.swing.JButton();
        Button_1 = new javax.swing.JButton();
        Button_4 = new javax.swing.JButton();
        Button_0 = new javax.swing.JButton();
        Button_8 = new javax.swing.JButton();
        Button_2 = new javax.swing.JButton();
        Button_5 = new javax.swing.JButton();
        Button_9 = new javax.swing.JButton();
        Button_e = new javax.swing.JButton();
        Button_space = new javax.swing.JButton();
        Button_D = new javax.swing.JButton();
        Button_asterisk = new javax.swing.JButton();
        Button_6 = new javax.swing.JButton();
        Button_C = new javax.swing.JButton();
        Button_less = new javax.swing.JButton();
        Button_3 = new javax.swing.JButton();
        jButton_separator = new javax.swing.JButton();
        Button_plus = new javax.swing.JButton();
        Button_equal = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();        

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Polynomial Calculator Of Two Variables");
        setBackground(java.awt.Color.lightGray);

        Button_7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/7.png"))); // NOI18N
        Button_7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Button_7.setName("button_7"); // NOI18N
        Button_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_7ActionPerformed(evt);
            }
        });

        Button_1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/1.png"))); // NOI18N
        Button_1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Button_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_1ActionPerformed(evt);
            }
        });

        Button_4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/4.png"))); // NOI18N
        Button_4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Button_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_4ActionPerformed(evt);
            }
        });

        Button_0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/0.png"))); // NOI18N
        Button_0.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Button_0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_0ActionPerformed(evt);
            }
        });

        Button_8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/8.png"))); // NOI18N
        Button_8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Button_8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_8ActionPerformed(evt);
            }
        });

        Button_2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/2.png"))); // NOI18N
        Button_2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Button_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_2ActionPerformed(evt);
            }
        });

        Button_5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/5.png"))); // NOI18N
        Button_5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Button_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_5ActionPerformed(evt);
            }
        });

        Button_9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/9.png"))); // NOI18N
        Button_9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Button_9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_9ActionPerformed(evt);
            }
        });

        Button_e.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/e.png"))); // NOI18N
        Button_e.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Button_e.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {                
                eval_ActionPerformed(evt);
            }
        });

        Button_space.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/space.png"))); // NOI18N
        Button_space.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Button_space.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	Button_spaceActionPerformed(evt);
            }
        });

        Button_D.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/D.png"))); // NOI18N
        Button_D.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Button_D.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_DActionPerformed(evt);
            }
        });

        Button_asterisk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/asterisco.png"))); // NOI18N
        Button_asterisk.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Button_asterisk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_asteriskActionPerformed(evt);
            }
        });

        Button_6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/6.png"))); // NOI18N
        Button_6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Button_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_6ActionPerformed(evt);
            }
        });

        Button_C.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/C.png"))); // NOI18N
        Button_C.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Button_C.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_CActionPerformed(evt);
            }
        });

        Button_less.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/menos.png"))); // NOI18N
        Button_less.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Button_less.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_lessActionPerformed(evt);
            }
        });

        Button_3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/3.png"))); // NOI18N
        Button_3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Button_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_3ActionPerformed(evt);
            }
        });

        jButton_separator.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/separator.png"))); // NOI18N
        jButton_separator.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton_separator.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_separatorActionPerformed(evt);
            }
        });

        Button_plus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/mas.png"))); // NOI18N
        Button_plus.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Button_plus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_plusActionPerformed(evt);
            }
        });

        Button_equal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/igual.png"))); // NOI18N
        Button_equal.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Button_equal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                equalActionPerformed(evt);
            }
        });

        jTextField1.setEditable(false);
        jTextField1.setBackground(java.awt.Color.gray);
        jTextField1.setFont(new java.awt.Font("Arial", 1, 20)

        );
        jTextField1.setForeground(java.awt.Color.white);
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jTextField1.setName(""); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jTextField1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Button_4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Button_7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Button_5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(Button_6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(Button_asterisk, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Button_8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(Button_9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(Button_e, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Button_1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(Button_2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Button_0, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(Button_space, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton_separator, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(Button_plus, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Button_3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(Button_less, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Button_D, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Button_C, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Button_equal, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(60, 60, 60))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Button_7, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button_8, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button_9, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button_e, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button_D, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Button_4, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button_5, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button_asterisk, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button_C, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button_6, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(Button_1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Button_2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(Button_less, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Button_3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Button_0, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_separator, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Button_space, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Button_plus, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(Button_equal, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Button_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_7ActionPerformed
       jTextField1.setText(jTextField1.getText() + "7" );
    }//GEN-LAST:event_Button_7ActionPerformed

    private void Button_8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_8ActionPerformed
        jTextField1.setText(jTextField1.getText() + "8" );
    }//GEN-LAST:event_Button_8ActionPerformed

    private void Button_9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_9ActionPerformed
        jTextField1.setText(jTextField1.getText() + "9" );
    }//GEN-LAST:event_Button_9ActionPerformed

    private void Button_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_4ActionPerformed
       jTextField1.setText(jTextField1.getText() + "4" );
    }//GEN-LAST:event_Button_4ActionPerformed

    private void Button_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_5ActionPerformed
       jTextField1.setText(jTextField1.getText() + "5" );
    }//GEN-LAST:event_Button_5ActionPerformed

    private void Button_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_6ActionPerformed
        jTextField1.setText(jTextField1.getText() + "6" );
    }//GEN-LAST:event_Button_6ActionPerformed

    private void Button_asteriskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_asteriskActionPerformed
    	if (myTokenizer.verifyInput(jTextField1.getText())){
        	_polynomialList.add(facade._myCalc.joinPolynomial(jTextField1.getText()));
        	_operator.add("*");
        	jTextField1.setText("");
        }
        else {
        	if (_polynomialList.size() == 1){
        		_operator.add("*");
            	jTextField1.setText("");
        	}
        	else {
        		jTextField1.setText("Syntax Error");
        	}
        }
    }//GEN-LAST:event_Button_asteriskActionPerformed

    private void Button_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_1ActionPerformed
        jTextField1.setText(jTextField1.getText() + "1" );
    }//GEN-LAST:event_Button_1ActionPerformed

    private void Button_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_2ActionPerformed
        jTextField1.setText(jTextField1.getText() + "2" );
    }//GEN-LAST:event_Button_2ActionPerformed

    private void Button_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_3ActionPerformed
       jTextField1.setText(jTextField1.getText() + "3" );
    }//GEN-LAST:event_Button_3ActionPerformed

    private void Button_lessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_lessActionPerformed        
        if (myTokenizer.verifyInput(jTextField1.getText())){
        	_polynomialList.add(facade._myCalc.joinPolynomial(jTextField1.getText()));
        	_operator.add("-");
        	jTextField1.setText("");
        }
        else {
        	if (_polynomialList.size() == 1){
        		_operator.add("-");
            	jTextField1.setText("");
        	}
        	else {
        		jTextField1.setText("-");
        	}
        }
    }//GEN-LAST:event_Button_lessActionPerformed

    private void eval_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_lessActionPerformed        
    	if (myTokenizer.verifyInput(jTextField1.getText())){
        	_polynomialList.add(facade._myCalc.joinPolynomial(jTextField1.getText()));
        	_operator.add("e");
        	jTextField1.setText("");
        }
        else {
        	if (_polynomialList.size() == 1){
        		_operator.add("e");
            	jTextField1.setText("");
        	}
        	else {
        		jTextField1.setText("Syntax Error");
        	}
        }
    }
    
    private void Button_0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_0ActionPerformed
       jTextField1.setText(jTextField1.getText() + "0" );
    }//GEN-LAST:event_Button_0ActionPerformed

    private void Button_spaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_spaceActionPerformed
        jTextField1.setText(jTextField1.getText() + " " );
    }//GEN-LAST:event_Button_spaceActionPerformed

    private void Button_plusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_plusActionPerformed    	 
    	if (myTokenizer.verifyInput(jTextField1.getText())){    		
        	_polynomialList.add(facade._myCalc.joinPolynomial(jTextField1.getText()));
        	_operator.add("+");
        	jTextField1.setText("");
        }
        else {
        	if (_polynomialList.size() == 1){
        		_operator.add("+");
            	jTextField1.setText("");
        	}
        	else {
        		jTextField1.setText("Syntax Error");
        	}
        }
    }//GEN-LAST:event_Button_plusActionPerformed

    private void equalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_plusActionPerformed    	
    	if (myTokenizer.verifyInput(jTextField1.getText())){
    		_polynomialList.add(facade._myCalc.joinPolynomial(jTextField1.getText()));
    		Polynomial tmp = _polynomialList.get(0);
    		if (_polynomialList.size() >= _operator.size()){
        		for (int i = 0; i < _operator.size(); i++){
        			if (_operator.get(i).equals("+")){
        				tmp = tmp.plus(_polynomialList.get(i+1));
                		jTextField1.setText(tmp.toString());
        			}
        			else if (_operator.get(i).equals("-")){
        				tmp = tmp.minus(_polynomialList.get(i+1));
                		jTextField1.setText(tmp.toString());
        			}
        			else if (_operator.get(i).equals("*")){
        				tmp = tmp.multiply(_polynomialList.get(i+1));        				
                		jTextField1.setText(tmp.toString());
        			}
        			else if (_operator.get(i).equals("e")){
        				String[] numbers = jTextField1.getText().split(" ");
        		    	try{
        		    		int x = java.lang.Integer.parseInt(numbers[0]);
        		    		int y = java.lang.Integer.parseInt(numbers[1]);
        		            jTextField1.setText("" +tmp.evaluate(x, y));        		            
        		    	}catch(Exception e){
        		    		jTextField1.setText("Syntax Error");
        		    	}     			
        			}
        		}    
        		_polynomialList.clear();
        		_operator.clear();
            }
            else {
            	jTextField1.setText("Missing an argument");
            }
    	}
        else {
        	if (_polynomialList.size() == 1){
        		if(_operator.get(0).equals("e")){
        			String[] numbers = jTextField1.getText().split(" ");
    		    	try{
    		    		int x = java.lang.Integer.parseInt(numbers[0]);
    		    		int y = java.lang.Integer.parseInt(numbers[1]);
    		            jTextField1.setText("" +_polynomialList.get(0).evaluate(x, y));
    		            _polynomialList.clear();
    	        		_operator.clear();
    		    	}catch(Exception e){
    		    		jTextField1.setText("Syntax Error");
    		    	} 
        		}
        	}
        	else {
        		jTextField1.setText("Syntax Error");
        	}
        }
    }    
    
    private void jButton_separatorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_separatorActionPerformed
        jTextField1.setText(jTextField1.getText() + "|" );
    }//GEN-LAST:event_jButton_separatorActionPerformed

    private void Button_CActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_CActionPerformed
        jTextField1.setText("");
        _polynomialList.clear();
    }//GEN-LAST:event_Button_CActionPerformed

    private void Button_DActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_DActionPerformed
        if (jTextField1.getText().length() != 0){
        	jTextField1.setText(jTextField1.getText().substring(0, jTextField1.getText().length()-1) );
        }
    }//GEN-LAST:event_Button_DActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CaculatorInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CaculatorInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CaculatorInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CaculatorInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CaculatorInterface().setVisible(true);
            }
        });
    }    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_0;
    private javax.swing.JButton Button_1;
    private javax.swing.JButton Button_2;
    private javax.swing.JButton Button_3;
    private javax.swing.JButton Button_4;
    private javax.swing.JButton Button_5;
    private javax.swing.JButton Button_6;
    private javax.swing.JButton Button_7;
    private javax.swing.JButton Button_8;
    private javax.swing.JButton Button_9;
    private javax.swing.JButton Button_C;
    private javax.swing.JButton Button_D;
    private javax.swing.JButton Button_asterisk;
    private javax.swing.JButton Button_e;
    private javax.swing.JButton Button_equal;
    private javax.swing.JButton Button_less;
    private javax.swing.JButton Button_plus;
    private javax.swing.JButton Button_space;
    private javax.swing.JButton jButton_separator;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
